name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    
    - name: Install LLVM
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-dev libclang-dev
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Run LOC check
      run: |
        python3 scripts/count_loc.py
    
    - name: Run tests
      run: |
        poetry run pytest
    
    - name: Run demo scan (dry-run)
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        poetry run memsage scan demo/tiny-game/ --cost-dry-run --max-cost 5.00
    
    - name: Build package
      run: |
        poetry build
    
    - name: Check package metadata
      run: |
        poetry run python -c "
        import toml
        data = toml.load('pyproject.toml')
        assert data['tool']['poetry']['version'] == '0.9.0'
        assert 'name' in data['tool']['poetry']
        assert 'description' in data['tool']['poetry']
        assert 'authors' in data['tool']['poetry']
        print('Package metadata validation passed')
        " 